apiVersion: apps/v1
kind: Deployment
metadata:
  name: preview-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preview-app
  template:
    metadata:
      labels:
        app: preview-app
    spec:
      containers:
      - name: preview-app
        image: 430695042378.dkr.ecr.us-east-1.amazonaws.com/preview-app:d3b78d8e4e0e471e6ba05d346fc405cf0c8ad6ab
        ports:
        - containerPort: 3000