apiVersion: apps/v1
kind: Deployment
metadata:
  name: preview-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preview-app
  template:
    metadata:
      labels:
        app: preview-app
    spec:
      containers:
      - name: preview-app
        image: 430695042378.dkr.ecr.us-east-1.amazonaws.com/preview-app:f90a2afeb78128f66d245210111b39c5d6f01bd4
        ports:
        - containerPort: 3000